//! Token definitions for the ETA language.
//!
//! The [`Token`] enum is derived using the [`logos`] crate, which generates
//! an efficient lexer from the regex and literal annotations on each variant.
//! Whitespace (spaces, tabs, form feeds) is skipped automatically between tokens.
//!
//! Line comments start with `//` and are also skipped.

use logos::Logos;
use std::fmt;
use unescaper;
#[derive(Default, Debug, Clone, PartialEq)]
pub enum LexicalError {
    #[default]
    InvalidToken,
}

impl From<()> for LexicalError {
    fn from(_: ()) -> Self {
        LexicalError::InvalidToken
    }
}

impl fmt::Display for LexicalError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LexicalError::InvalidToken => write!(f, "invalid token"),
        }
    }
}

/// A token in the ETA language.
///
/// Tokens are generated by the [`logos`] crate. Each variant is annotated with either
/// a `#[token("...")]` for exact matches or `#[regex("...")]` for pattern matches.
///
/// Newline tokens are not consumed by the parser directly — they are
/// used by the [`Lexer`](crate::lexer::Lexer) for automatic semicolon insertion
/// and never reach the parser.
#[derive(Logos, Debug, Clone, PartialEq)]
#[logos(skip r"[ \t\f]+")] // Ignore this regex pattern between tokens
pub enum Token {
    /// An identifier or variable name,
    #[regex("[_a-zA-Z][_0-9a-zA-Z]*", |lex| lex.slice().to_string())]
    Var(String),
    /// An integer literal. Parsed eagerly as `i64`.
    #[regex("[0-9]+", |lex| lex.slice().parse::<i64>().unwrap())]
    Int(i64),
    // Found in logos example Json parser
    #[regex(r#""([^"\\\x00-\x1F]|\\(["\\bnfrt/]|u[a-fA-F0-9]{4}))*""#, |lex| {let slice = lex.slice().to_owned();
                                                                            let inner = slice[1..slice.len()-1].to_string(); // Removes "Hello" -> Hello
                                                                            unescaper::unescape(&inner).unwrap_or_else(|_| inner.to_string())
    })]
    StringLiteral(String),

    /// Line comments (`// ...`) — skipped by the lexer.
    #[regex(r"//[^\n]*", logos::skip)]
    // Binary Operators
    #[token("+")]
    Plus,
    #[token("-")]
    Minus,
    #[token("!")]
    Bang,
    #[token(".")]
    Dot,
    #[token("*")]
    Asterisk,
    #[token("/")]
    Div,
    #[token("%")]
    Mod,
    #[token("<")]
    LessThan,
    #[token("<=")]
    LessEqual,
    #[token(">")]
    GreaterThan,
    #[token(">=")]
    GreaterEqual,

    #[token("==")]
    DoubleEquals,
    #[token("!=")]
    NotEquals,

    #[token("&")]
    And,
    #[token("|")]
    Bar,

    #[token("=")]
    Equal,
    // Parenthesis
    #[token("(")]
    LParen,
    #[token(")")]
    RParen,
    #[token("{")]
    LBrace,
    #[token("}")]
    RBrace,
    #[token("[")]
    LBrack,
    #[token("]")]
    RBrack,

    #[token(";")]
    Semicolon,
    #[token(",")]
    Comma,
    #[token(":")]
    Colon,

    // Keywords
    #[token("return")]
    Return,
    #[token("record")]
    Record,
    #[token("if")]
    If,
    #[token("else")]
    Else,
    #[token("while")]
    While,
    #[token("int")]
    TInt,
    #[token("bool")]
    TBool,
    #[token("true")]
    True,
    #[token("false")]
    False,
    // Easier for Semicolon Insertion
    #[regex(r"\n+")]
    Newline,
    #[end]
    Eof,
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lex_one(input: &str) -> Token {
        let mut lex = Token::lexer(input);
        let tok = lex.next().unwrap().unwrap();
        assert!(lex.next().is_none(), "Lexer produced extra Tokens");
        tok
    }

    #[test]
    fn test_simple_string() {
        let tok = lex_one(r#""Hello""#);
        assert_eq!(tok, Token::StringLiteral("Hello".into()));
    }

    #[test]
    fn test_string_with_spaces() {
        let tok = lex_one(r#""Hello World""#);
        assert_eq!(tok, Token::StringLiteral("Hello World".into()));
    }

    #[test]
    fn test_string_with_escape_quote() {
        let tok = lex_one(r#""He said \"hi\"""#);
        assert_eq!(tok, Token::StringLiteral("He said \"hi\"".into()));
    }

    #[test]
    fn test_string_with_unicode_escape() {
        let tok = lex_one(r#""\u0041""#); // 'A'
        assert_eq!(tok, Token::StringLiteral("A".into()));
    }
}
