//! Array allocation, initialization and concatenation.
//!
//! # Design decision: array layout
//!
//! An array's length lives in the 8 bytes *before* its data, at `arr[-8]`.
//! Allocation returns a pointer past that header, so element `i` sits at offset
//! `i * size` and indexing needs no correction for it. `length()` is the only
//! thing that looks backwards, and it is generated by `add_length`.
//!
//! Multi-dimensional arrays are built one dimension at a time:
//! `array_init_helper` recurses over the declared dimensions and emits a loop
//! per level that fills each slot with a freshly allocated inner array.
//! Dimensions declared without a size are filtered out beforehand, so only the
//! sized ones are allocated here.

use super::builder::InstrBuilder;
use super::*;
impl WtacGen {
    /// Allocates a dynamically-sized array via `eta_malloc`.
    ///
    /// Same as [`create_simple_array`](Self::create_simple_array) but the length
    /// is a runtime value instead of a constant.
    fn create_variable_array(
        &mut self,
        arr_len: &W::Value,
        elem_t: &Type,
    ) -> (Vec<W::Instruction>, W::Value) {
        let mut b = InstrBuilder::new(self);
        let elem_size = b.i64_const(types::get_size(elem_t) as i64);
        let size_val = b.binary(W::BinaryOp::Mult, arr_len.clone(), elem_size, W::WType::I64);

        let with_header = b.binary(W::BinaryOp::Add, size_val, b.i64_const(8), W::WType::I64);

        let size_i32 = b.wrap(with_header);

        let raw_ptr = b.call("eta_malloc", vec![size_i32], W::WType::I32);

        let mem_ptr = b.gene.mem_of_wtac_var(&raw_ptr, 0, &W::WType::I64);
        b.copy_to(arr_len.clone(), mem_ptr, W::WType::I64);

        let data_ptr = b.binary(W::BinaryOp::Add, raw_ptr, b.i32_const(8), W::WType::I32);

        (b.finish(), data_ptr)
    }

    /// Allocates a fixed-size array via `eta_malloc`.
    ///
    /// Computes the byte size as `len * size(elem) + 8` (8 bytes for the length
    /// header), calls `eta_malloc`, writes the length at offset 0, then returns
    /// a pointer past the header (so element 0 is at offset 0).
    pub(super) fn create_simple_array(
        &mut self,
        arr_len: usize,
        elem_t: &Type,
    ) -> (Vec<W::Instruction>, W::Value) {
        // compute arr_size * size(elem_t) + 8
        // _ 8 because we store the length at arr[-1]
        let mut b = InstrBuilder::new(self);
        let offset = arr_len * types::get_size(elem_t) + 8;

        let raw_ptr = b.call(
            "eta_malloc",
            vec![b.i32_const(offset.try_into().unwrap())],
            W::WType::I32,
        );

        let mem_ptr = b.gene.mem_of_wtac_var(&raw_ptr, 0, &W::WType::I64);
        b.copy_to(
            W::Value::Imm(arr_len as i64, W::WType::I64),
            mem_ptr,
            W::WType::I64,
        );

        // Type Bool so we do not have to wrap it
        let data_ptr = b.binary(W::BinaryOp::Add, raw_ptr, b.i32_const(8), W::WType::I32);

        (b.finish(), data_ptr)
    }

    /// Recursively initializes multi-dimensional arrays.
    ///
    /// For `int[2][3]`, first allocates the outer array of size 2, then loops
    /// to allocate an inner array of size 3 for each element and stores the
    /// pointer. The recursion handles arbitrary nesting depth.
    pub(super) fn array_init_helper(
        &mut self,
        elem_t: &Type,
        dims: &[&ast::Expression],
    ) -> (Vec<W::Instruction>, W::Value) {
        // Loop for initialzing the values
        match dims {
            [] => panic!("Internal Error: Should not be empty"),
            // Base case
            [e] => {
                let (e_instr, e_res) = self.gen_and_convert_expression(e);
                let (arr_instr, arr_ptr) = self.create_variable_array(&e_res, elem_t);
                ([e_instr, arr_instr].concat(), arr_ptr)
            }
            [e, rest @ ..] => {
                let (e_instr, e_res) = self.gen_and_convert_expression(e);

                let (arr_instr, arr_ptr) = self.create_variable_array(&e_res, elem_t);

                let t = match elem_t {
                    Type::Array { elem_type } => elem_type,
                    _ => panic!("Internal Error: Mismatch between types and dimension"),
                };
                // These inner instructions will be looped!
                let (inner_instr, inner_ptr) = self.array_init_helper(t, rest);
                // ctr = 0
                // while (ctr < res_e) { // bound of array
                // inner_instr // The content of the inner array is created here in the loop [2][3] the array of size 3 is created here 2 times!
                // offset = ctr * sizeof (t) // size of array elemt to generate offset
                // ptr = arr_ptr + offset
                // [ptr] = inner_ptr
                // }
                // Set up a loop manually
                // Loop as long as ctr < e_res
                // let mut b = InstrBuilder::new(self);
                // let ctr= b.copy(b.i64_const(0), Type::Int);
                let ctr = self.make_wtac_var(W::WType::I64);
                let init_ctr_instr = W::Instruction::Copy {
                    src: W::Value::Imm(0, W::WType::I64),
                    dst: ctr.clone(),
                    t: W::WType::I64,
                };
                let guard = self.make_wtac_var(W::WType::I32);
                let guard_instr = W::Instruction::Binary {
                    op: W::BinaryOp::Lt,
                    src1: ctr.clone(),
                    src2: e_res,
                    dst: guard.clone(),
                    t: W::WType::I64,
                };
                // let guard = b.compare(W::BinaryOp::Lt, ctr.clone(), e_res, Type::Int);

                let loop_add_instr = W::Instruction::Binary {
                    op: W::BinaryOp::Add,
                    src1: ctr.clone(),
                    src2: W::Value::Imm(1, W::WType::I64),
                    dst: ctr.clone(),
                    t: W::WType::I64,
                };

                let (offset_instrs, ptr) = self.get_offset_instr(&arr_ptr, elem_t, &ctr);

                let copy_arr_instr = W::Instruction::Copy {
                    src: inner_ptr,
                    dst: self.mem_of_wtac_var(&ptr, 0, &convert_type(elem_t)),
                    t: convert_type(elem_t),
                };

                let loop_body = [
                    inner_instr,
                    offset_instrs,
                    vec![copy_arr_instr, loop_add_instr],
                ]
                .concat();
                let while_block = self.get_while_loop(guard_instr, guard, loop_body);

                let instrs = [e_instr, arr_instr, vec![init_ctr_instr, while_block]].concat();

                (instrs, arr_ptr)
            }
        }
    }

    // Generates instructions to compute `base_ptr + index * size(elem_type)`.
    ///
    /// Returns the offsetted pointer and the instructions that compute it.
    /// The index is multiplied and wrapped to i32 since WASM addresses are 32-bit.
    fn get_offset_instr(
        &mut self,
        arr: &W::Value,
        elem_ty: &Type,
        offset: &W::Value,
    ) -> (Vec<W::Instruction>, W::Value) {
        let mut b = InstrBuilder::new(self);
        let ptr = b.ptr_offset(arr, offset, elem_ty);
        (b.finish(), ptr)
    }

    // ─── Control flow helpers ─────────────────────────

    /// Generates a `while` loop as a `Block` containing a `Loop`.
    ///
    /// The condition is evaluated at the top of the loop body. If false,
    /// the loop exits via `br` to the outer block. The end of the loop body
    /// branches back to the loop header.
    fn get_while_loop(
        &mut self,
        cond: W::Instruction,
        guard: W::Value,
        mut body: Vec<W::Instruction>,
    ) -> W::Instruction {
        let (exit_lbl, loop_lbl) = self.fresh_label_pair("while_end", "while_loop");

        let mut b = InstrBuilder::new(self);
        b.extend(vec![cond]);
        let guard_not = b.unary(W::UnaryOp::Not, guard.clone(), W::WType::I32);
        b.brif(&guard_not, &exit_lbl);

        let loop_guard = b.finish();
        // So that it loops
        body.push(W::Instruction::Br(loop_lbl.clone()));
        let loop_malloc = W::Instruction::Loop {
            label: loop_lbl,
            body: [loop_guard, body].concat(),
        };

        W::Instruction::Block {
            label: exit_lbl,
            body: vec![loop_malloc],
        }
    }

    pub(super) fn gen_array_concat(
        &mut self,
        e1: &ast::Expression,
        e2: &ast::Expression,
        e_ty: &Type,
    ) -> (Vec<W::Instruction>, W::Value) {
        debug!("Array Addition");
        let elem_ty = match &e_ty {
            Type::Array { elem_type } => elem_type.clone(),
            _ => unreachable!(""),
        };
        let (e1_instr, v_e1) = self.gen_and_convert_expression(e1);
        let (e2_instr, v_e2) = self.gen_and_convert_expression(e2);
        let mut b = InstrBuilder::new(self);
        b.extend(e1_instr);
        b.extend(e2_instr);
        // l = length(a1)
        // r = length(a2)
        // n = l + r
        // arr = eta_malloc(n)
        // ctr = 0
        // while ctr < l {
        // arr[ctr] = a[ctr]
        // ctr += 1
        // }
        // ctr_r = 0
        //  while ctr_r < r {
        // arr[ctr] = a[ctr_r]
        // ctr_r += 1
        // ctr += 1
        // }
        // Get lenght of both arrays.
        let len_left = b.call("length", vec![v_e1.clone()], W::WType::I64);
        let len_right = b.call("length", vec![v_e2.clone()], W::WType::I64);
        let len_full = b.binary(
            W::BinaryOp::Add,
            len_left.clone(),
            len_right.clone(),
            W::WType::I64,
        );

        let (arr_instr, new_arr) = b.gene.create_variable_array(&len_full, &elem_ty);
        b.extend(arr_instr);

        let copy_left = b
            .gene
            .build_copy_loop(&v_e1, &new_arr, &elem_ty, &len_left, None);
        let copy_right =
            b.gene
                .build_copy_loop(&v_e2, &new_arr, &elem_ty, &len_right, Some(&len_left));
        b.extend(copy_left);
        b.extend(copy_right);

        (b.finish(), new_arr)
    }

    fn build_copy_loop(
        &mut self,
        src_arr: &W::Value,
        dst_arr: &W::Value,
        elem_ty: &Type,
        bound: &W::Value,
        dst_offset_start: Option<&W::Value>,
    ) -> Vec<W::Instruction> {
        let mut b = InstrBuilder::new(self);
        let ctr = b.copy(b.i64_const(0), W::WType::I64);
        let dst_ctr = match dst_offset_start {
            Some(start) => b.copy(start.clone(), W::WType::I64),
            None => b.copy(b.i64_const(0), W::WType::I64),
        };

        // First Loop
        let guard = b.compare(W::BinaryOp::Lt, ctr.clone(), bound.clone(), W::WType::I64);

        let mut setup = b.finish();
        let mut b = InstrBuilder::new(self);
        let src_ptr = b.ptr_offset(src_arr, &ctr, elem_ty);
        let dst_ptr = b.ptr_offset(dst_arr, &dst_ctr, elem_ty);
        let src_mem = b.gene.mem_of_wtac_var(&src_ptr, 0, &convert_type(elem_ty));
        let dst_mem = b.gene.mem_of_wtac_var(&dst_ptr, 0, &convert_type(elem_ty));
        b.copy_to(src_mem, dst_mem, convert_type(elem_ty));

        // Update the Counters
        b.binary_to(
            W::BinaryOp::Add,
            ctr.clone(),
            b.i64_const(1),
            ctr.clone(),
            W::WType::I64,
        );
        b.binary_to(
            W::BinaryOp::Add,
            dst_ctr.clone(),
            b.i64_const(1),
            dst_ctr.clone(),
            W::WType::I64,
        );

        let body = b.finish();

        // Extract guard instruction from setup
        let guard_instr = setup.pop().unwrap();
        let while_block = self.get_while_loop(guard_instr, guard, body);
        setup.push(while_block);
        setup
    }

    /// Generates the built-in `length(arr)` function.
    ///
    /// The array length is stored at `arr[-8]` (8 bytes before the data pointer),
    /// so `length` subtracts 8 from the pointer and loads an i64.
    pub(super) fn add_length(&mut self) -> W::TopLevel {
        // length takes an array as argument and returns an int
        self.curr_f_data = FunData {
            offset: 0,
            rsp: W::Value::Var("Dummy".to_string()),
            ret_ptr: None,
            locals: vec![],
        };

        let a_name = self.fresh("tmp");
        // Use bool here since it has same length as any array
        self.tchecker
            .symtab
            .add_local_var(a_name.clone(), Type::Bool);

        let mut b = InstrBuilder::new(self);
        let arr_ptr = W::Value::Var(a_name.clone());
        let header_ptr = b.binary(W::BinaryOp::Sub, arr_ptr, b.i32_const(8), W::WType::I32);
        let header_mem = b.gene.mem_of_wtac_var(&header_ptr, 0, &W::WType::I64);
        let len = b.copy(header_mem, W::WType::I64);
        b.br("func_exit");

        let func_block = W::Instruction::Block {
            label: "func_exit".to_string(),
            body: b.finish(),
        };
        let ret_instr = W::Instruction::Return(Some(len));
        let f_type = W::WType::FunType {
            param_type: vec![W::WType::I32],
            ret_type: Some(Box::new(W::WType::I64)),
        };

        W::TopLevel::Function {
            name: "length".to_string(),
            body: vec![func_block, ret_instr],
            params: vec![a_name],
            f_type,
            locals: self.curr_f_data.locals.clone(),
        }
    }
}
